server:
  port: 8080

spring:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  data:
    mongodb:
      database: test
      port: 27017

  kafka:
    bootstrap-servers: realKafka:9092
    consumer:
      auto-offset-reset: earliest

logging:
  level:
    root: INFO
    com.agilesolutions.mcp: DEBUG
    org.springframework.ai: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

twelvedata:
  api:
    url: https://api.twelvedata.com/
    key: demo